version: 0.2

phases:
  install:
    commands:
      - pip install awscli
      - pip install c7n
  build:
    commands:
      - custodian run -s output s3globalgrant-lambda-policy.yml --region us-east-2
      - custodian run -s output cat-ec2tagcompliance-stop-policy.yml --region us-east-2
