policies:

- name: s3-global-access
  resource: s3
  mode: 
    type: config-rule
    role: arn:aws:iam::047283044064:role/CCustodianLambda
  filters:
    - type: global-grants
  actions:
    - type: delete-global-grants
      grantees:
        - "http://acs.amazonaws.com/groups/global/AllUsers"
        - "http://acs.amazonaws.com/groups/global/AuthenticatedUsers"
